// Generated package API contract. Do not edit.
export interface ApiEntrypointDefinition {
  readonly packageName: string;
  readonly version: string;
  readonly subpath: string;
  readonly importName: string;
  readonly slug: string;
  readonly symbolSet: string;
}

export const apiManifest: readonly ApiEntrypointDefinition[] = [
  {
    packageName: '@askrjs/askr',
    version: '0.0.88',
    subpath: '.',
    importName: '@askrjs/askr',
    slug: 'root',
    symbolSet: 'symbols0',
  },
  {
    packageName: '@askrjs/askr',
    version: '0.0.88',
    subpath: './boot',
    importName: '@askrjs/askr/boot',
    slug: 'boot',
    symbolSet: 'symbols1',
  },
  {
    packageName: '@askrjs/askr',
    version: '0.0.88',
    subpath: './components',
    importName: '@askrjs/askr/components',
    slug: 'components',
    symbolSet: 'symbols2',
  },
  {
    packageName: '@askrjs/askr',
    version: '0.0.88',
    subpath: './control',
    importName: '@askrjs/askr/control',
    slug: 'control',
    symbolSet: 'symbols3',
  },
  {
    packageName: '@askrjs/askr',
    version: '0.0.88',
    subpath: './foundations',
    importName: '@askrjs/askr/foundations',
    slug: 'foundations',
    symbolSet: 'symbols4',
  },
  {
    packageName: '@askrjs/askr',
    version: '0.0.88',
    subpath: './foundations/utilities',
    importName: '@askrjs/askr/foundations/utilities',
    slug: 'foundations--utilities',
    symbolSet: 'symbols5',
  },
  {
    packageName: '@askrjs/askr',
    version: '0.0.88',
    subpath: './foundations/interactions',
    importName: '@askrjs/askr/foundations/interactions',
    slug: 'foundations--interactions',
    symbolSet: 'symbols6',
  },
  {
    packageName: '@askrjs/askr',
    version: '0.0.88',
    subpath: './foundations/state',
    importName: '@askrjs/askr/foundations/state',
    slug: 'foundations--state',
    symbolSet: 'symbols7',
  },
  {
    packageName: '@askrjs/askr',
    version: '0.0.88',
    subpath: './foundations/structures',
    importName: '@askrjs/askr/foundations/structures',
    slug: 'foundations--structures',
    symbolSet: 'symbols8',
  },
  {
    packageName: '@askrjs/askr',
    version: '0.0.88',
    subpath: './foundations/icon',
    importName: '@askrjs/askr/foundations/icon',
    slug: 'foundations--icon',
    symbolSet: 'symbols9',
  },
  {
    packageName: '@askrjs/askr',
    version: '0.0.88',
    subpath: './resources',
    importName: '@askrjs/askr/resources',
    slug: 'resources',
    symbolSet: 'symbols10',
  },
  {
    packageName: '@askrjs/askr',
    version: '0.0.88',
    subpath: './data',
    importName: '@askrjs/askr/data',
    slug: 'data',
    symbolSet: 'symbols11',
  },
  {
    packageName: '@askrjs/askr',
    version: '0.0.88',
    subpath: './testing',
    importName: '@askrjs/askr/testing',
    slug: 'testing',
    symbolSet: 'symbols12',
  },
  {
    packageName: '@askrjs/askr',
    version: '0.0.88',
    subpath: './fx',
    importName: '@askrjs/askr/fx',
    slug: 'fx',
    symbolSet: 'symbols13',
  },
  {
    packageName: '@askrjs/askr',
    version: '0.0.88',
    subpath: './router',
    importName: '@askrjs/askr/router',
    slug: 'router',
    symbolSet: 'symbols14',
  },
  {
    packageName: '@askrjs/askr',
    version: '0.0.88',
    subpath: './actions',
    importName: '@askrjs/askr/actions',
    slug: 'actions',
    symbolSet: 'symbols15',
  },
  {
    packageName: '@askrjs/askr',
    version: '0.0.88',
    subpath: './ssr',
    importName: '@askrjs/askr/ssr',
    slug: 'ssr',
    symbolSet: 'symbols16',
  },
  {
    packageName: '@askrjs/askr',
    version: '0.0.88',
    subpath: './ssg',
    importName: '@askrjs/askr/ssg',
    slug: 'ssg',
    symbolSet: 'symbols17',
  },
  {
    packageName: '@askrjs/askr',
    version: '0.0.88',
    subpath: './jsx-runtime',
    importName: '@askrjs/askr/jsx-runtime',
    slug: 'jsx-runtime',
    symbolSet: 'symbols18',
  },
  {
    packageName: '@askrjs/askr',
    version: '0.0.88',
    subpath: './jsx-dev-runtime',
    importName: '@askrjs/askr/jsx-dev-runtime',
    slug: 'jsx-dev-runtime',
    symbolSet: 'symbols19',
  },
  {
    packageName: '@askrjs/auth',
    version: '0.0.8',
    subpath: '.',
    importName: '@askrjs/auth',
    slug: 'root',
    symbolSet: 'symbols20',
  },
  {
    packageName: '@askrjs/auth',
    version: '0.0.8',
    subpath: './jwt',
    importName: '@askrjs/auth/jwt',
    slug: 'jwt',
    symbolSet: 'symbols21',
  },
  {
    packageName: '@askrjs/auth',
    version: '0.0.8',
    subpath: './oidc',
    importName: '@askrjs/auth/oidc',
    slug: 'oidc',
    symbolSet: 'symbols22',
  },
  {
    packageName: '@askrjs/auth',
    version: '0.0.8',
    subpath: './saml',
    importName: '@askrjs/auth/saml',
    slug: 'saml',
    symbolSet: 'symbols23',
  },
  {
    packageName: '@askrjs/auth',
    version: '0.0.8',
    subpath: './mfa',
    importName: '@askrjs/auth/mfa',
    slug: 'mfa',
    symbolSet: 'symbols24',
  },
  {
    packageName: '@askrjs/auth',
    version: '0.0.8',
    subpath: './webauthn-client',
    importName: '@askrjs/auth/webauthn-client',
    slug: 'webauthn-client',
    symbolSet: 'symbols25',
  },
  {
    packageName: '@askrjs/charts',
    version: '0.1.5',
    subpath: '.',
    importName: '@askrjs/charts',
    slug: 'root',
    symbolSet: 'symbols26',
  },
  {
    packageName: '@askrjs/charts',
    version: '0.1.5',
    subpath: './styles',
    importName: '@askrjs/charts/styles',
    slug: 'styles',
    symbolSet: 'symbols27',
  },
  {
    packageName: '@askrjs/fetch',
    version: '0.0.4',
    subpath: '.',
    importName: '@askrjs/fetch',
    slug: 'root',
    symbolSet: 'symbols28',
  },
  {
    packageName: '@askrjs/fetch',
    version: '0.0.4',
    subpath: './middleware',
    importName: '@askrjs/fetch/middleware',
    slug: 'middleware',
    symbolSet: 'symbols29',
  },
  {
    packageName: '@askrjs/i18n',
    version: '0.0.3',
    subpath: '.',
    importName: '@askrjs/i18n',
    slug: 'root',
    symbolSet: 'symbols30',
  },
  {
    packageName: '@askrjs/logos',
    version: '0.0.6',
    subpath: '.',
    importName: '@askrjs/logos',
    slug: 'root',
    symbolSet: 'symbols31',
  },
  {
    packageName: '@askrjs/lucide',
    version: '0.0.8',
    subpath: '.',
    importName: '@askrjs/lucide',
    slug: 'root',
    symbolSet: 'symbols32',
  },
  {
    packageName: '@askrjs/monaco',
    version: '0.0.7',
    subpath: '.',
    importName: '@askrjs/monaco',
    slug: 'root',
    symbolSet: 'symbols33',
  },
  {
    packageName: '@askrjs/monaco',
    version: '0.0.7',
    subpath: './monaco-editor',
    importName: '@askrjs/monaco/monaco-editor',
    slug: 'monaco-editor',
    symbolSet: 'symbols34',
  },
  {
    packageName: '@askrjs/node',
    version: '0.0.8',
    subpath: '.',
    importName: '@askrjs/node',
    slug: 'root',
    symbolSet: 'symbols35',
  },
  {
    packageName: '@askrjs/node',
    version: '0.0.8',
    subpath: './mcp',
    importName: '@askrjs/node/mcp',
    slug: 'mcp',
    symbolSet: 'symbols36',
  },
  {
    packageName: '@askrjs/otel',
    version: '0.0.4',
    subpath: '.',
    importName: '@askrjs/otel',
    slug: 'root',
    symbolSet: 'symbols37',
  },
  {
    packageName: '@askrjs/schema',
    version: '0.0.5',
    subpath: '.',
    importName: '@askrjs/schema',
    slug: 'root',
    symbolSet: 'symbols38',
  },
  {
    packageName: '@askrjs/server',
    version: '0.0.11',
    subpath: '.',
    importName: '@askrjs/server',
    slug: 'root',
    symbolSet: 'symbols39',
  },
  {
    packageName: '@askrjs/server',
    version: '0.0.11',
    subpath: './router',
    importName: '@askrjs/server/router',
    slug: 'router',
    symbolSet: 'symbols40',
  },
  {
    packageName: '@askrjs/server',
    version: '0.0.11',
    subpath: './http',
    importName: '@askrjs/server/http',
    slug: 'http',
    symbolSet: 'symbols41',
  },
  {
    packageName: '@askrjs/server',
    version: '0.0.11',
    subpath: './middleware',
    importName: '@askrjs/server/middleware',
    slug: 'middleware',
    symbolSet: 'symbols42',
  },
  {
    packageName: '@askrjs/server',
    version: '0.0.11',
    subpath: './askr',
    importName: '@askrjs/server/askr',
    slug: 'askr',
    symbolSet: 'symbols43',
  },
  {
    packageName: '@askrjs/server',
    version: '0.0.11',
    subpath: './auth',
    importName: '@askrjs/server/auth',
    slug: 'auth',
    symbolSet: 'symbols44',
  },
  {
    packageName: '@askrjs/server',
    version: '0.0.11',
    subpath: './openapi',
    importName: '@askrjs/server/openapi',
    slug: 'openapi',
    symbolSet: 'symbols45',
  },
  {
    packageName: '@askrjs/server',
    version: '0.0.11',
    subpath: './mcp',
    importName: '@askrjs/server/mcp',
    slug: 'mcp',
    symbolSet: 'symbols46',
  },
  {
    packageName: '@askrjs/testing',
    version: '0.0.5',
    subpath: '.',
    importName: '@askrjs/testing',
    slug: 'root',
    symbolSet: 'symbols47',
  },
  {
    packageName: '@askrjs/themes',
    version: '0.0.23',
    subpath: '.',
    importName: '@askrjs/themes',
    slug: 'root',
    symbolSet: 'symbols48',
  },
  {
    packageName: '@askrjs/themes',
    version: '0.0.23',
    subpath: './default',
    importName: '@askrjs/themes/default',
    slug: 'default',
    symbolSet: 'symbols48',
  },
  {
    packageName: '@askrjs/themes',
    version: '0.0.23',
    subpath: './presets',
    importName: '@askrjs/themes/presets',
    slug: 'presets',
    symbolSet: 'symbols48',
  },
  {
    packageName: '@askrjs/themes',
    version: '0.0.23',
    subpath: './components',
    importName: '@askrjs/themes/components',
    slug: 'components',
    symbolSet: 'symbols49',
  },
  {
    packageName: '@askrjs/themes',
    version: '0.0.23',
    subpath: './theme',
    importName: '@askrjs/themes/theme',
    slug: 'theme',
    symbolSet: 'symbols50',
  },
  {
    packageName: '@askrjs/themes',
    version: '0.0.23',
    subpath: './ssr',
    importName: '@askrjs/themes/ssr',
    slug: 'ssr',
    symbolSet: 'symbols51',
  },
  {
    packageName: '@askrjs/themes',
    version: '0.0.23',
    subpath: './default/tokens.css',
    importName: '@askrjs/themes/default/tokens.css',
    slug: 'default--tokens.css',
    symbolSet: 'symbols48',
  },
  {
    packageName: '@askrjs/themes',
    version: '0.0.23',
    subpath: './default/foundations.css',
    importName: '@askrjs/themes/default/foundations.css',
    slug: 'default--foundations.css',
    symbolSet: 'symbols48',
  },
  {
    packageName: '@askrjs/themes',
    version: '0.0.23',
    subpath: './default/input.css',
    importName: '@askrjs/themes/default/input.css',
    slug: 'default--input.css',
    symbolSet: 'symbols48',
  },
  {
    packageName: '@askrjs/themes',
    version: '0.0.23',
    subpath: './default/label.css',
    importName: '@askrjs/themes/default/label.css',
    slug: 'default--label.css',
    symbolSet: 'symbols48',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: '.',
    importName: '@askrjs/ui',
    slug: 'root',
    symbolSet: 'symbols52',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './avatar',
    importName: '@askrjs/ui/avatar',
    slug: 'avatar',
    symbolSet: 'symbols53',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './button',
    importName: '@askrjs/ui/button',
    slug: 'button',
    symbolSet: 'symbols54',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './checkbox',
    importName: '@askrjs/ui/checkbox',
    slug: 'checkbox',
    symbolSet: 'symbols55',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './input',
    importName: '@askrjs/ui/input',
    slug: 'input',
    symbolSet: 'symbols56',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './form',
    importName: '@askrjs/ui/form',
    slug: 'form',
    symbolSet: 'symbols57',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './label',
    importName: '@askrjs/ui/label',
    slug: 'label',
    symbolSet: 'symbols58',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './progress',
    importName: '@askrjs/ui/progress',
    slug: 'progress',
    symbolSet: 'symbols59',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './progress-circle',
    importName: '@askrjs/ui/progress-circle',
    slug: 'progress-circle',
    symbolSet: 'symbols60',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './radio-group',
    importName: '@askrjs/ui/radio-group',
    slug: 'radio-group',
    symbolSet: 'symbols61',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './select',
    importName: '@askrjs/ui/select',
    slug: 'select',
    symbolSet: 'symbols62',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './slider',
    importName: '@askrjs/ui/slider',
    slug: 'slider',
    symbolSet: 'symbols63',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './switch',
    importName: '@askrjs/ui/switch',
    slug: 'switch',
    symbolSet: 'symbols64',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './table',
    importName: '@askrjs/ui/table',
    slug: 'table',
    symbolSet: 'symbols65',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './virtual-list',
    importName: '@askrjs/ui/virtual-list',
    slug: 'virtual-list',
    symbolSet: 'symbols66',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './virtual-table',
    importName: '@askrjs/ui/virtual-table',
    slug: 'virtual-table',
    symbolSet: 'symbols67',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './textarea',
    importName: '@askrjs/ui/textarea',
    slug: 'textarea',
    symbolSet: 'symbols68',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './toggle',
    importName: '@askrjs/ui/toggle',
    slug: 'toggle',
    symbolSet: 'symbols69',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './toggle-group',
    importName: '@askrjs/ui/toggle-group',
    slug: 'toggle-group',
    symbolSet: 'symbols70',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './visually-hidden',
    importName: '@askrjs/ui/visually-hidden',
    slug: 'visually-hidden',
    symbolSet: 'symbols71',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './accordion',
    importName: '@askrjs/ui/accordion',
    slug: 'accordion',
    symbolSet: 'symbols72',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './alert-dialog',
    importName: '@askrjs/ui/alert-dialog',
    slug: 'alert-dialog',
    symbolSet: 'symbols73',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './collapsible',
    importName: '@askrjs/ui/collapsible',
    slug: 'collapsible',
    symbolSet: 'symbols74',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './dialog',
    importName: '@askrjs/ui/dialog',
    slug: 'dialog',
    symbolSet: 'symbols75',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './dismissable-layer',
    importName: '@askrjs/ui/dismissable-layer',
    slug: 'dismissable-layer',
    symbolSet: 'symbols76',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './dropdown',
    importName: '@askrjs/ui/dropdown',
    slug: 'dropdown',
    symbolSet: 'symbols77',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './focus-scope',
    importName: '@askrjs/ui/focus-scope',
    slug: 'focus-scope',
    symbolSet: 'symbols78',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './hover-card',
    importName: '@askrjs/ui/hover-card',
    slug: 'hover-card',
    symbolSet: 'symbols79',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './menu',
    importName: '@askrjs/ui/menu',
    slug: 'menu',
    symbolSet: 'symbols80',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './menubar',
    importName: '@askrjs/ui/menubar',
    slug: 'menubar',
    symbolSet: 'symbols81',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './popover',
    importName: '@askrjs/ui/popover',
    slug: 'popover',
    symbolSet: 'symbols82',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './scroll-area',
    importName: '@askrjs/ui/scroll-area',
    slug: 'scroll-area',
    symbolSet: 'symbols83',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './toast',
    importName: '@askrjs/ui/toast',
    slug: 'toast',
    symbolSet: 'symbols84',
  },
  {
    packageName: '@askrjs/ui',
    version: '0.0.26',
    subpath: './tooltip',
    importName: '@askrjs/ui/tooltip',
    slug: 'tooltip',
    symbolSet: 'symbols85',
  },
  {
    packageName: '@askrjs/vite',
    version: '0.0.12',
    subpath: '.',
    importName: '@askrjs/vite',
    slug: 'root',
    symbolSet: 'symbols86',
  },
  {
    packageName: '@askrjs/vite',
    version: '0.0.12',
    subpath: './server',
    importName: '@askrjs/vite/server',
    slug: 'server',
    symbolSet: 'symbols87',
  },
  {
    packageName: '@askrjs/vite',
    version: '0.0.12',
    subpath: './image',
    importName: '@askrjs/vite/image',
    slug: 'image',
    symbolSet: 'symbols88',
  },
];
