export {
  CatalogSection,
  CodeSnippetBlock,
  HeroActionGrid,
  HeroChipRow,
  HeroStatGrid,
  InputRequirementsList,
  PageSection as ShowcaseSection,
  SectionHead,
  SpotlightSignals,
  ThemeExampleCard,
  type CatalogGroup,
  type HeroAction,
  type HeroChipLink,
  type HeroStat,
  type InputRequirement,
  type PageSectionProps as ShowcaseSectionProps,
  type SectionHeadProps,
  type SpotlightSignal,
  type ThemeExampleProps,
} from './page-primitives';
