import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import ts from 'typescript';
import { formatGeneratedTypeScript } from './format-generated';

type PackageLock = {
  packages: Record<string, unknown>;
};

type PackageManifest = {
  version: string;
  exports?: Record<string, unknown>;
};

type Entrypoint = {
  packageName: string;
  version: string;
  subpath: string;
  importName: string;
  declarationPath: string;
};

type ApiSymbol = {
  name: string;
  anchor: string;
  signature: string;
  typeOnly: boolean;
};

const root = process.cwd();
const snapshotPath = resolve(root, 'src/pages/docs/api-snapshot.ts');
const manifestPath = resolve(root, 'src/pages/docs/api-manifest.ts');
const packageLock = JSON.parse(
  readFileSync(resolve(root, 'package-lock.json'), 'utf8')
) as PackageLock;
const packageNames = Object.keys(packageLock.packages)
  .filter((path) => path.startsWith('node_modules/@askrjs/'))
  .map((path) => path.slice('node_modules/'.length))
  .filter((name) => name !== '@askrjs/cli')
  .sort();

function exportedTypesTarget(value: unknown): string | undefined {
  if (typeof value === 'string') return undefined;
  if (!value || typeof value !== 'object') return undefined;
  if ('types' in value && typeof value.types === 'string') return value.types;
  for (const nested of Object.values(value)) {
    const target = exportedTypesTarget(nested);
    if (target) return target;
  }
}

const entrypoints: Entrypoint[] = [];
for (const packageName of packageNames) {
  const packageDirectory = resolve(root, 'node_modules', packageName);
  const manifest = JSON.parse(
    readFileSync(resolve(packageDirectory, 'package.json'), 'utf8')
  ) as PackageManifest;
  for (const [subpath, target] of Object.entries(manifest.exports ?? {})) {
    if (subpath.includes('*') || subpath === './package.json') continue;
    const typesTarget = exportedTypesTarget(target);
    if (!typesTarget) continue;
    const declarationPath = resolve(packageDirectory, typesTarget);
    if (!existsSync(declarationPath)) continue;
    entrypoints.push({
      packageName,
      version: manifest.version,
      subpath,
      importName:
        subpath === '.' ? packageName : `${packageName}/${subpath.slice(2)}`,
      declarationPath,
    });
  }
}

const program = ts.createProgram(
  entrypoints.map((entrypoint) => entrypoint.declarationPath),
  {
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    skipLibCheck: true,
  }
);
const checker = program.getTypeChecker();

function anchorFor(value: string) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .toLowerCase();
}

function signatureFor(symbol: ts.Symbol) {
  const declaration = symbol.valueDeclaration ?? symbol.declarations?.[0];
  if (!declaration) return symbol.name;
  try {
    const type = checker.getTypeOfSymbolAtLocation(symbol, declaration);
    const rendered = checker.typeToString(
      type,
      declaration,
      ts.TypeFormatFlags.NoTruncation |
        ts.TypeFormatFlags.UseAliasDefinedOutsideCurrentScope
    );
    return `${symbol.name}: ${rendered}`;
  } catch {
    return symbol.name;
  }
}

const symbolSets: Record<string, ApiSymbol[]> = {};
const symbolSetNames = new Map();
const snapshot = entrypoints.map((entrypoint) => {
  let symbolSet = symbolSetNames.get(entrypoint.declarationPath);
  if (!symbolSet) {
    const source = program.getSourceFile(entrypoint.declarationPath);
    const moduleSymbol = source && checker.getSymbolAtLocation(source);
    const usedAnchors = new Map();
    const symbols = moduleSymbol
      ? checker
          .getExportsOfModule(moduleSymbol)
          .filter((symbol) => symbol.name !== 'default')
          .map((symbol) => {
            const baseAnchor = anchorFor(symbol.name) || 'export';
            const count = usedAnchors.get(baseAnchor) ?? 0;
            usedAnchors.set(baseAnchor, count + 1);
            return {
              name: symbol.name,
              anchor: count === 0 ? baseAnchor : `${baseAnchor}-${count + 1}`,
              signature: signatureFor(symbol),
              typeOnly: !symbol.valueDeclaration,
            };
          })
          .sort((left, right) => left.name.localeCompare(right.name))
      : [];
    symbolSet = `symbols${symbolSetNames.size}`;
    symbolSetNames.set(entrypoint.declarationPath, symbolSet);
    symbolSets[symbolSet] = symbols;
  }
  return {
    packageName: entrypoint.packageName,
    version: entrypoint.version,
    subpath: entrypoint.subpath,
    importName: entrypoint.importName,
    slug:
      entrypoint.subpath === '.'
        ? 'root'
        : entrypoint.subpath.slice(2).replaceAll('/', '--'),
    symbolSet,
  };
});

const unformattedManifestSource =
  `// Generated by scripts/generate-api-snapshot.ts. Do not edit.\n` +
  `export const apiManifest = ${JSON.stringify(snapshot, null, 2)} as const;\n`;
const unformattedSnapshotSource =
  `// Generated by scripts/generate-api-snapshot.ts. Do not edit.\n` +
  `export const apiSymbolSets = ${JSON.stringify(symbolSets, null, 2)} as const;\n`;
const manifestSource = formatGeneratedTypeScript(
  manifestPath,
  unformattedManifestSource
);
const snapshotSource = formatGeneratedTypeScript(
  snapshotPath,
  unformattedSnapshotSource
);

const existingManifest = existsSync(manifestPath)
  ? readFileSync(manifestPath, 'utf8')
  : '';
const existingSnapshot = existsSync(snapshotPath)
  ? readFileSync(snapshotPath, 'utf8')
  : '';
if (process.argv.includes('--check')) {
  if (
    existingManifest !== manifestSource ||
    existingSnapshot !== snapshotSource
  ) {
    console.error('API snapshot is out of date. Run npm run docs:api.');
    process.exitCode = 1;
  }
} else {
  await import('node:fs/promises').then(({ writeFile }) =>
    Promise.all([
      writeFile(manifestPath, manifestSource),
      writeFile(snapshotPath, snapshotSource),
    ])
  );
  console.log(
    `Generated ${snapshot.length} entrypoints and ${Object.values(symbolSets).reduce((sum, symbols) => sum + symbols.length, 0)} unique declaration symbols.`
  );
}
